name: Run autotests


on:
  workflow_dispatch:
    inputs:
      deploymaent_target:
        description: select tests run
        required: true
        type: choice
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Copy source code
        uses: actions/checkout@v4
      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.4"
      - name: install dependencies 
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytests -v
